#!/usr/bin/env python3
"""Turn a TTF into an antialiased VLW font, as a C++ header for M5GFX.

    python3 scripts/vlwfont.py NAME SIZE FONT.ttf [--tracking EM] [--chars TEXT] > src/fonts/NAME.h

VLW is the format LovyanGFX / M5GFX load at runtime (`VLWfont`): a table of
glyph metrics, then each glyph as 8-bit coverage. The header holds the file's
bytes plus the two numbers the firmware needs that VLW doesn't carry: the
height of a capital, and the advance of a space. Needs Pillow.

--tracking adds letter-spacing, in em. --chars limits the font to the
characters given (default: printable ASCII).
"""
import argparse
import struct
import sys

from PIL import Image, ImageDraw, ImageFont


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("name")
    parser.add_argument("size", type=int)
    parser.add_argument("ttf")
    parser.add_argument("--tracking", type=float, default=0.0)
    parser.add_argument("--chars", default="".join(chr(c) for c in range(0x21, 0x7F)))
    args = parser.parse_args()

    font = ImageFont.truetype(args.ttf, args.size)
    track = args.tracking * args.size

    def advance(ch):
        return max(1, round(font.getlength(ch) + track))

    glyphs = []  # (code, height, width, advance, top above baseline, left, coverage)
    for ch in sorted(set(args.chars) - {" "}):
        # Origin on the baseline, at the pen position.
        left, top, right, bottom = font.getbbox(ch, anchor="ls")
        w, h = right - left, bottom - top
        image = Image.new("L", (w, h), 0)
        ImageDraw.Draw(image).text((-left, -top), ch, font=font, fill=255, anchor="ls")
        glyphs.append((ord(ch), h, w, advance(ch), -top, left, image.tobytes()))

    def top_of(ch, fallback):
        return -font.getbbox(ch, anchor="ls")[1] if ch in args.chars else fallback

    ascent = max(g[4] for g in glyphs)
    descent = max(g[1] - g[4] for g in glyphs)
    cap = top_of("H", top_of("0", ascent))

    data = struct.pack(">6i", len(glyphs), 11, args.size, 0, ascent, descent)
    for code, h, w, adv, dy, dx, _ in glyphs:
        data += struct.pack(">7i", code, h, w, adv, dy, dx, 0)
    for glyph in glyphs:
        data += glyph[6]

    out = sys.stdout
    out.write("#pragma once\n\n")
    out.write("// Generated by scripts/vlwfont.py (see scripts/fonts.sh). Don't edit.\n")
    out.write(f"// {args.ttf.rsplit('/', 1)[-1]} at {args.size}px, tracking {args.tracking}em, {len(glyphs)} glyphs.\n")
    out.write("#include <cstdint>\n\n")
    out.write("namespace fontdata {\n\n")
    out.write(f"inline constexpr int {args.name}_cap = {cap};\n")
    out.write(f"inline constexpr int {args.name}_space = {advance(' ')};\n")
    out.write(f"inline constexpr uint8_t {args.name}[] = {{\n")
    for i in range(0, len(data), 24):
        out.write("    " + ",".join(str(b) for b in data[i : i + 24]) + ",\n")
    out.write("};\n\n}  // namespace fontdata\n")


if __name__ == "__main__":
    main()
