#!/usr/bin/env python3
"""Rasterize a TTF into a 1-bit EpdFont header (lib/EpdFont/EpdFontData.h).

A minimal stand-in for CrossPoint's fontconvert.py: uncompressed, no kerning,
no ligatures. Fine for monospaced UI fonts. Sizes are in pixels.

  python3 scripts/fontconvert.py plexmono_14_bold 14 fonts/IBMPlexMono/IBMPlexMono-Bold.ttf
  python3 scripts/fontconvert.py plexmono_136_clock 136 fonts/IBMPlexMono/IBMPlexMono-Regular.ttf \
      --chars " -0123456789:" --tracking -0.05

The shipped headers are made by scripts/fonts.sh.

Writes lib/EpdFont/builtinFonts/<name>.h. Needs Pillow.
"""

import argparse
import pathlib

from PIL import Image, ImageDraw, ImageFont

OUT_DIR = pathlib.Path(__file__).resolve().parent.parent / "lib/EpdFont/builtinFonts"
ASCII = "".join(chr(c) for c in range(0x20, 0x7F))


def rasterize(font, ch, tracking_px):
    """Return (width, height, left, top, advance_fp4, packed_bytes) for one glyph."""
    advance = round((font.getlength(ch) + tracking_px) * 16)
    x0, y0, x1, y1 = font.getbbox(ch, anchor="ls")
    w, h = x1 - x0, y1 - y0
    if w <= 0 or h <= 0 or ch == " ":
        return 0, 0, 0, 0, advance, b""
    img = Image.new("L", (w, h), 0)
    ImageDraw.Draw(img).text((-x0, -y0), ch, font=font, anchor="ls", fill=255)
    # getbbox spans the advance, not the ink; crop to the thresholded ink.
    ink = img.point(lambda v: 255 if v >= 128 else 0).getbbox()
    if ink is None:
        return 0, 0, 0, 0, advance, b""
    img = img.crop(ink)
    x0, y0 = x0 + ink[0], y0 + ink[1]
    w, h = img.size
    px = img.load()
    bits = [1 if px[x, y] >= 128 else 0 for y in range(h) for x in range(w)]
    packed = bytearray()
    for i in range(0, len(bits), 8):
        chunk = bits[i : i + 8] + [0] * (8 - len(bits[i : i + 8]))
        packed.append(sum(b << (7 - j) for j, b in enumerate(chunk)))
    return w, h, x0, -y0, advance, bytes(packed)


def intervals(codepoints):
    out = []
    for i, cp in enumerate(codepoints):
        if out and cp == out[-1][1] + 1:
            out[-1][1] = cp
        else:
            out.append([cp, cp, i])
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("name")
    ap.add_argument("size", type=int, help="pixel size")
    ap.add_argument("ttf")
    ap.add_argument("--chars", default=ASCII, help="characters to include (default: printable ASCII)")
    ap.add_argument("--tracking", type=float, default=0.0, help="letter spacing baked into advances, in em")
    args = ap.parse_args()

    font = ImageFont.truetype(args.ttf, args.size)
    ascent, descent = font.getmetrics()
    codepoints = sorted({ord(c) for c in args.chars})

    bitmap = bytearray()
    glyphs = []
    for cp in codepoints:
        w, h, left, top, adv, data = rasterize(font, chr(cp), args.tracking * args.size)
        glyphs.append((w, h, adv, left, top, len(data), len(bitmap), cp))
        bitmap += data

    n = args.name
    lines = [
        "/**",
        " * generated by scripts/fontconvert.py",
        f" * name: {n}",
        f" * size: {args.size}px",
        " * mode: 1-bit",
        f" * source: {pathlib.Path(args.ttf).name}",
        f" * tracking: {args.tracking}em",
        " */",
        "#pragma once",
        '#include "EpdFontData.h"',
        "",
        f"static const uint8_t {n}Bitmaps[{max(1, len(bitmap))}] = {{",
    ]
    data = bytes(bitmap) or b"\0"
    for i in range(0, len(data), 16):
        lines.append("    " + " ".join(f"0x{b:02X}," for b in data[i : i + 16]))
    lines.append("};")
    lines.append("")
    lines.append(f"static const EpdGlyph {n}Glyphs[] = {{")
    for w, h, adv, left, top, length, offset, cp in glyphs:
        lines.append(f"    {{ {w}, {h}, {adv}, {left}, {top}, {length}, {offset} }}, // U+{cp:04X}")
    lines.append("};")
    lines.append("")
    lines.append(f"static const EpdUnicodeInterval {n}Intervals[] = {{")
    for first, last, offset in intervals(codepoints):
        lines.append(f"    {{ 0x{first:X}, 0x{last:X}, 0x{offset:X} }},")
    lines.append("};")
    lines.append("")
    lines += [
        f"static const EpdFontData {n} = {{",
        f"    {n}Bitmaps,",
        f"    {n}Glyphs,",
        f"    {n}Intervals,",
        f"    {len(intervals(codepoints))},",
        f"    {ascent + descent},  // advanceY",
        f"    {ascent},  // ascender",
        f"    {-descent},  // descender",
        "    false,  // is2Bit",
        "    nullptr,  // groups: uncompressed",
        "    0,",
        "    nullptr,",
        "    nullptr,  // no kerning or ligatures",
        "};",
        "",
    ]
    out = OUT_DIR / f"{n}.h"
    out.write_text("\n".join(lines))
    print(f"wrote {out} ({len(codepoints)} glyphs, {len(bitmap)} bitmap bytes)")


if __name__ == "__main__":
    main()
